### PR TITLE
Mafioso Implementation

### PR DESCRIPTION
**Pull request by dchanman**
One thing we should discuss:

If a role is blocked, do they display the message
"You were unable to perform your action"

or does it still display the same message
"You attempted to.. blablabla"

Mafioso is implemented to display
"You were unable to perform your action"
if he is blocked. If he is unblocked he shows
"You attemped to kill ... target"

Is this what we want?

### CODE REVIEW

**Comment by maknoon** [comment]
wait what's in this branch again, why are there so many commits

**Comment by dchanman** [comment]
Should only be the Mafioso implementation, the original branch might have been dirty. I'll clean this up when I have the chance

**Comment by dchanman** [comment]
For now, just look at the changes tab

**Comment by maknoon** [comment]
the master branch has deprecated stuff then? ok this will be our cleanup branch

**Comment by dchanman** [comment]
No do cleanup on a separate branch, this is meant to only contain a new implementation of mafioso

**Comment by maknoon** [comment]
ok. we should merge this PR first then. maybe when we meet i guess we can go over everything?

**Comment by dchanman** [comment]
Yep, you can code review it and merge it if you like it

**Comment by maknoon** [comment]
k i'll do the code review today, have some free time later for it

**Comment by maknoon** [comment]
code review done, looks good, i'll merge it in a bit

**Pull request merged**
